### ISSUE TITLE
Feature request: 增加伪粗体以支持「楷体」与「仿宋」字体加粗

### ISSUE THREAD

**Issue by OrangeX4** [nju-lug/nju-thesis-typst#1]
https://github.com/typst/typst/issues/394

https://github.com/typst/typst/issues/725

**Comment by MaxZZG** [comment]
可以先用一下 [https://github.com/csimide/cuti](url) 这个伪粗体包。

**Comment by OrangeX4** [comment]
感谢！目前还没来得及更新。

**Comment by OrangeX4** [comment]
已经更新。
