### ISSUE TITLE
Bug:figure里面的代码块中文字体不显示

### ISSUE THREAD

**Issue by zhengzavan** [nju-lug/nju-thesis-typst#4]
figure代码块里面出现中文会显示为豆腐块，字体测试页面仿宋和楷体等都是正常显示的，其他地方也是正常显示的

**Comment by zhengzavan** [comment]
没事了，我的问题没有安装等宽字体，字体测试页面忘了还有个等宽要显示；
安装这个就好了 https://github.com/adobe-fonts/source-han-mono

**Comment by zhengzavan** [comment]
翻了下源代码，没看到哪里应用了等宽字体，可能使忘了设置

#show raw: set text(font: ("Courier New", "Menlo", "IBM Plex Mono", "Source Han Sans HW SC", "Source Han Sans HW", "Noto Sans Mono CJK SC", "SimHei", "Heiti SC", "STHeiti"))

**Comment by OrangeX4** [comment]
感谢，我会看一下如何修复
